### ISSUE TITLE
[FEAT] 트윗작성 뷰 작성부분 UI 및 이벤트 처리 구현

### ISSUE THREAD

**Issue by Suyeon9911** [SOPT-Joint-Seminar-Twitter/Twitter-iOS#8]
## 💡 Feature Issue

트윗 작성하기뷰 작성하는 부분 UI 및 이벤트 처리 구현

## 🌿  To-do

- [x] 배경색 변경
- [x] 상단 취소, 트윗버튼 구현
- [x] 프로필 사진 + 텍스트 필드 구현 
- [x] 텍스트 필드 이벤트 처리 구현 -> 글자 있으면 트윗버튼 활성화
- [x] 키보드 이벤트 처리 : 올라와있는게 default로 유지하기 ! 
- [x] 데이터 전달 및 화면 전환하기 ! -> 프로필 뷰로 전환 + 트윗 올라가게 !

**Comment by Suyeon9911** [comment]
텍스트 뷰 플레이스 홀더 문제..

**Comment by Suyeon9911** [comment]
화면전환은 나중에 dismiss
