### ISSUE TITLE
[FEAT] 트윗작성뷰 키보드부분 UI 및 레이아웃 구현

### ISSUE THREAD

**Issue by Suyeon9911** [SOPT-Joint-Seminar-Twitter/Twitter-iOS#9]
## 💡 Feature Issue

트윗작성뷰에서 밑에 키보드랑 같이있는 부분 ui랑 레이아웃 구현 ~

## 🌿  To-do

- [x] 맨 아래 툴바 만들기 
- [x] 2번째 지구모양 안내 뷰 만들기
- [x] 컬렉션 뷰 만들기
- [x] 컬렉션 뷰 셀 만들기 
- [x] 컬렉션뷰 1,2번은 아이콘 / 그 뒤로는 사진들

**Comment by Suyeon9911** [comment]
컬렉션뷰가 옆으로 안넘어가는 오류 해결중..
